/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BitcoinTransactionService } from "../bitcoinTransaction.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BitcoinTransactionCreateInput } from "./BitcoinTransactionCreateInput";
import { BitcoinTransaction } from "./BitcoinTransaction";
import { BitcoinTransactionFindManyArgs } from "./BitcoinTransactionFindManyArgs";
import { BitcoinTransactionWhereUniqueInput } from "./BitcoinTransactionWhereUniqueInput";
import { BitcoinTransactionUpdateInput } from "./BitcoinTransactionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BitcoinTransactionControllerBase {
  constructor(
    protected readonly service: BitcoinTransactionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BitcoinTransaction })
  @nestAccessControl.UseRoles({
    resource: "BitcoinTransaction",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBitcoinTransaction(
    @common.Body() data: BitcoinTransactionCreateInput
  ): Promise<BitcoinTransaction> {
    return await this.service.createBitcoinTransaction({
      data: data,
      select: {
        bitcoinAmount: true,
        createdAt: true,
        date: true,
        id: true,
        transactionType: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BitcoinTransaction] })
  @ApiNestedQuery(BitcoinTransactionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BitcoinTransaction",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async bitcoinTransactions(
    @common.Req() request: Request
  ): Promise<BitcoinTransaction[]> {
    const args = plainToClass(BitcoinTransactionFindManyArgs, request.query);
    return this.service.bitcoinTransactions({
      ...args,
      select: {
        bitcoinAmount: true,
        createdAt: true,
        date: true,
        id: true,
        transactionType: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BitcoinTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BitcoinTransaction",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async bitcoinTransaction(
    @common.Param() params: BitcoinTransactionWhereUniqueInput
  ): Promise<BitcoinTransaction | null> {
    const result = await this.service.bitcoinTransaction({
      where: params,
      select: {
        bitcoinAmount: true,
        createdAt: true,
        date: true,
        id: true,
        transactionType: true,
        updatedAt: true,
        user: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BitcoinTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BitcoinTransaction",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBitcoinTransaction(
    @common.Param() params: BitcoinTransactionWhereUniqueInput,
    @common.Body() data: BitcoinTransactionUpdateInput
  ): Promise<BitcoinTransaction | null> {
    try {
      return await this.service.updateBitcoinTransaction({
        where: params,
        data: data,
        select: {
          bitcoinAmount: true,
          createdAt: true,
          date: true,
          id: true,
          transactionType: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BitcoinTransaction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BitcoinTransaction",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBitcoinTransaction(
    @common.Param() params: BitcoinTransactionWhereUniqueInput
  ): Promise<BitcoinTransaction | null> {
    try {
      return await this.service.deleteBitcoinTransaction({
        where: params,
        select: {
          bitcoinAmount: true,
          createdAt: true,
          date: true,
          id: true,
          transactionType: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
