/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FreelanceCategoryService } from "../freelanceCategory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FreelanceCategoryCreateInput } from "./FreelanceCategoryCreateInput";
import { FreelanceCategory } from "./FreelanceCategory";
import { FreelanceCategoryFindManyArgs } from "./FreelanceCategoryFindManyArgs";
import { FreelanceCategoryWhereUniqueInput } from "./FreelanceCategoryWhereUniqueInput";
import { FreelanceCategoryUpdateInput } from "./FreelanceCategoryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FreelanceCategoryControllerBase {
  constructor(
    protected readonly service: FreelanceCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FreelanceCategory })
  @nestAccessControl.UseRoles({
    resource: "FreelanceCategory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFreelanceCategory(
    @common.Body() data: FreelanceCategoryCreateInput
  ): Promise<FreelanceCategory> {
    return await this.service.createFreelanceCategory({
      data: data,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FreelanceCategory] })
  @ApiNestedQuery(FreelanceCategoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FreelanceCategory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async freelanceCategories(
    @common.Req() request: Request
  ): Promise<FreelanceCategory[]> {
    const args = plainToClass(FreelanceCategoryFindManyArgs, request.query);
    return this.service.freelanceCategories({
      ...args,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FreelanceCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FreelanceCategory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async freelanceCategory(
    @common.Param() params: FreelanceCategoryWhereUniqueInput
  ): Promise<FreelanceCategory | null> {
    const result = await this.service.freelanceCategory({
      where: params,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FreelanceCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FreelanceCategory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFreelanceCategory(
    @common.Param() params: FreelanceCategoryWhereUniqueInput,
    @common.Body() data: FreelanceCategoryUpdateInput
  ): Promise<FreelanceCategory | null> {
    try {
      return await this.service.updateFreelanceCategory({
        where: params,
        data: data,
        select: {
          categoryName: true,
          createdAt: true,
          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FreelanceCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FreelanceCategory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFreelanceCategory(
    @common.Param() params: FreelanceCategoryWhereUniqueInput
  ): Promise<FreelanceCategory | null> {
    try {
      return await this.service.deleteFreelanceCategory({
        where: params,
        select: {
          categoryName: true,
          createdAt: true,
          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
