/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SavingsAccountService } from "../savingsAccount.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SavingsAccountCreateInput } from "./SavingsAccountCreateInput";
import { SavingsAccount } from "./SavingsAccount";
import { SavingsAccountFindManyArgs } from "./SavingsAccountFindManyArgs";
import { SavingsAccountWhereUniqueInput } from "./SavingsAccountWhereUniqueInput";
import { SavingsAccountUpdateInput } from "./SavingsAccountUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SavingsAccountControllerBase {
  constructor(
    protected readonly service: SavingsAccountService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SavingsAccount })
  @nestAccessControl.UseRoles({
    resource: "SavingsAccount",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSavingsAccount(
    @common.Body() data: SavingsAccountCreateInput
  ): Promise<SavingsAccount> {
    return await this.service.createSavingsAccount({
      data: data,
      select: {
        balance: true,
        createdAt: true,
        dateOpened: true,
        id: true,
        rainyDayFund: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SavingsAccount] })
  @ApiNestedQuery(SavingsAccountFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SavingsAccount",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async savingsAccounts(
    @common.Req() request: Request
  ): Promise<SavingsAccount[]> {
    const args = plainToClass(SavingsAccountFindManyArgs, request.query);
    return this.service.savingsAccounts({
      ...args,
      select: {
        balance: true,
        createdAt: true,
        dateOpened: true,
        id: true,
        rainyDayFund: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SavingsAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavingsAccount",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async savingsAccount(
    @common.Param() params: SavingsAccountWhereUniqueInput
  ): Promise<SavingsAccount | null> {
    const result = await this.service.savingsAccount({
      where: params,
      select: {
        balance: true,
        createdAt: true,
        dateOpened: true,
        id: true,
        rainyDayFund: true,
        updatedAt: true,
        user: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SavingsAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavingsAccount",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSavingsAccount(
    @common.Param() params: SavingsAccountWhereUniqueInput,
    @common.Body() data: SavingsAccountUpdateInput
  ): Promise<SavingsAccount | null> {
    try {
      return await this.service.updateSavingsAccount({
        where: params,
        data: data,
        select: {
          balance: true,
          createdAt: true,
          dateOpened: true,
          id: true,
          rainyDayFund: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SavingsAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SavingsAccount",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSavingsAccount(
    @common.Param() params: SavingsAccountWhereUniqueInput
  ): Promise<SavingsAccount | null> {
    try {
      return await this.service.deleteSavingsAccount({
        where: params,
        select: {
          balance: true,
          createdAt: true,
          dateOpened: true,
          id: true,
          rainyDayFund: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
