/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PTransferCreateInput } from "./P2PTransferCreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateP2PTransferArgs {
  @ApiProperty({
    required: true,
    type: () => P2PTransferCreateInput,
  })
  @ValidateNested()
  @Type(() => P2PTransferCreateInput)
  @Field(() => P2PTransferCreateInput, { nullable: false })
  data!: P2PTransferCreateInput;
}

export { CreateP2PTransferArgs as CreateP2PTransferArgs };
