/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PTransferWhereUniqueInput } from "./P2PTransferWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteP2PTransferArgs {
  @ApiProperty({
    required: true,
    type: () => P2PTransferWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => P2PTransferWhereUniqueInput)
  @Field(() => P2PTransferWhereUniqueInput, { nullable: false })
  where!: P2PTransferWhereUniqueInput;
}

export { DeleteP2PTransferArgs as DeleteP2PTransferArgs };
