/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PTransferWhereInput } from "./P2PTransferWhereInput";
import { Type } from "class-transformer";

@ArgsType()
class P2PTransferCountArgs {
  @ApiProperty({
    required: false,
    type: () => P2PTransferWhereInput,
  })
  @Field(() => P2PTransferWhereInput, { nullable: true })
  @Type(() => P2PTransferWhereInput)
  where?: P2PTransferWhereInput;
}

export { P2PTransferCountArgs as P2PTransferCountArgs };
