/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PTransferWhereInput } from "./P2PTransferWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class P2PTransferListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => P2PTransferWhereInput,
  })
  @ValidateNested()
  @Type(() => P2PTransferWhereInput)
  @IsOptional()
  @Field(() => P2PTransferWhereInput, {
    nullable: true,
  })
  every?: P2PTransferWhereInput;

  @ApiProperty({
    required: false,
    type: () => P2PTransferWhereInput,
  })
  @ValidateNested()
  @Type(() => P2PTransferWhereInput)
  @IsOptional()
  @Field(() => P2PTransferWhereInput, {
    nullable: true,
  })
  some?: P2PTransferWhereInput;

  @ApiProperty({
    required: false,
    type: () => P2PTransferWhereInput,
  })
  @ValidateNested()
  @Type(() => P2PTransferWhereInput)
  @IsOptional()
  @Field(() => P2PTransferWhereInput, {
    nullable: true,
  })
  none?: P2PTransferWhereInput;
}
export { P2PTransferListRelationFilter as P2PTransferListRelationFilter };
