/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { P2PTransferWhereInput } from "./P2PTransferWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { P2PTransferOrderByInput } from "./P2PTransferOrderByInput";

@ArgsType()
class P2PTransferFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => P2PTransferWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => P2PTransferWhereInput, { nullable: true })
  @Type(() => P2PTransferWhereInput)
  where?: P2PTransferWhereInput;

  @ApiProperty({
    required: false,
    type: [P2PTransferOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [P2PTransferOrderByInput], { nullable: true })
  @Type(() => P2PTransferOrderByInput)
  orderBy?: Array<P2PTransferOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { P2PTransferFindManyArgs as P2PTransferFindManyArgs };
