/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FreelanceJobService } from "../freelanceJob.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FreelanceJobCreateInput } from "./FreelanceJobCreateInput";
import { FreelanceJob } from "./FreelanceJob";
import { FreelanceJobFindManyArgs } from "./FreelanceJobFindManyArgs";
import { FreelanceJobWhereUniqueInput } from "./FreelanceJobWhereUniqueInput";
import { FreelanceJobUpdateInput } from "./FreelanceJobUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FreelanceJobControllerBase {
  constructor(
    protected readonly service: FreelanceJobService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FreelanceJob })
  @nestAccessControl.UseRoles({
    resource: "FreelanceJob",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFreelanceJob(
    @common.Body() data: FreelanceJobCreateInput
  ): Promise<FreelanceJob> {
    return await this.service.createFreelanceJob({
      data: data,
      select: {
        category: true,
        createdAt: true,
        id: true,
        isBlocked: true,
        jobDescription: true,
        jobTitle: true,
        paymentMethod: true,
        postedDate: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FreelanceJob] })
  @ApiNestedQuery(FreelanceJobFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FreelanceJob",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async freelanceJobs(@common.Req() request: Request): Promise<FreelanceJob[]> {
    const args = plainToClass(FreelanceJobFindManyArgs, request.query);
    return this.service.freelanceJobs({
      ...args,
      select: {
        category: true,
        createdAt: true,
        id: true,
        isBlocked: true,
        jobDescription: true,
        jobTitle: true,
        paymentMethod: true,
        postedDate: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FreelanceJob })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FreelanceJob",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async freelanceJob(
    @common.Param() params: FreelanceJobWhereUniqueInput
  ): Promise<FreelanceJob | null> {
    const result = await this.service.freelanceJob({
      where: params,
      select: {
        category: true,
        createdAt: true,
        id: true,
        isBlocked: true,
        jobDescription: true,
        jobTitle: true,
        paymentMethod: true,
        postedDate: true,
        updatedAt: true,
        user: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FreelanceJob })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FreelanceJob",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFreelanceJob(
    @common.Param() params: FreelanceJobWhereUniqueInput,
    @common.Body() data: FreelanceJobUpdateInput
  ): Promise<FreelanceJob | null> {
    try {
      return await this.service.updateFreelanceJob({
        where: params,
        data: data,
        select: {
          category: true,
          createdAt: true,
          id: true,
          isBlocked: true,
          jobDescription: true,
          jobTitle: true,
          paymentMethod: true,
          postedDate: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FreelanceJob })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FreelanceJob",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFreelanceJob(
    @common.Param() params: FreelanceJobWhereUniqueInput
  ): Promise<FreelanceJob | null> {
    try {
      return await this.service.deleteFreelanceJob({
        where: params,
        select: {
          category: true,
          createdAt: true,
          id: true,
          isBlocked: true,
          jobDescription: true,
          jobTitle: true,
          paymentMethod: true,
          postedDate: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
