/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "../../validators";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumFilterPhotoDuration } from "./EnumFilterPhotoDuration";
import { EnumFilterPhotoSharingDuration } from "./EnumFilterPhotoSharingDuration";
import { EnumFilterProfileColor } from "./EnumFilterProfileColor";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumFilterUserProfileColor } from "./EnumFilterUserProfileColor";

@InputType()
class FilterCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  avatar?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  emoji?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  photo?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumFilterPhotoDuration,
  })
  @IsEnum(EnumFilterPhotoDuration)
  @IsOptional()
  @Field(() => EnumFilterPhotoDuration, {
    nullable: true,
  })
  photoDuration?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumFilterPhotoSharingDuration,
  })
  @IsEnum(EnumFilterPhotoSharingDuration)
  @IsOptional()
  @Field(() => EnumFilterPhotoSharingDuration, {
    nullable: true,
  })
  photoSharingDuration?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumFilterProfileColor,
  })
  @IsEnum(EnumFilterProfileColor)
  @IsOptional()
  @Field(() => EnumFilterProfileColor, {
    nullable: true,
  })
  profileColor?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumFilterUserProfileColor,
  })
  @IsEnum(EnumFilterUserProfileColor)
  @IsOptional()
  @Field(() => EnumFilterUserProfileColor, {
    nullable: true,
  })
  userProfileColor?: "Option1" | null;
}

export { FilterCreateInput as FilterCreateInput };
