/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { JsonFilter } from "../../util/JsonFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { EnumFilterPhotoDuration } from "./EnumFilterPhotoDuration";
import { EnumFilterPhotoSharingDuration } from "./EnumFilterPhotoSharingDuration";
import { EnumFilterProfileColor } from "./EnumFilterProfileColor";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { EnumFilterUserProfileColor } from "./EnumFilterUserProfileColor";

@InputType()
class FilterWhereInput {
  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  avatar?: JsonFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  emoji?: JsonFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  photo?: JsonFilter;

  @ApiProperty({
    required: false,
    enum: EnumFilterPhotoDuration,
  })
  @IsEnum(EnumFilterPhotoDuration)
  @IsOptional()
  @Field(() => EnumFilterPhotoDuration, {
    nullable: true,
  })
  photoDuration?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumFilterPhotoSharingDuration,
  })
  @IsEnum(EnumFilterPhotoSharingDuration)
  @IsOptional()
  @Field(() => EnumFilterPhotoSharingDuration, {
    nullable: true,
  })
  photoSharingDuration?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumFilterProfileColor,
  })
  @IsEnum(EnumFilterProfileColor)
  @IsOptional()
  @Field(() => EnumFilterProfileColor, {
    nullable: true,
  })
  profileColor?: "Option1";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumFilterUserProfileColor,
  })
  @IsEnum(EnumFilterUserProfileColor)
  @IsOptional()
  @Field(() => EnumFilterUserProfileColor, {
    nullable: true,
  })
  userProfileColor?: "Option1";
}

export { FilterWhereInput as FilterWhereInput };
