/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BankTransferService } from "../bankTransfer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BankTransferCreateInput } from "./BankTransferCreateInput";
import { BankTransfer } from "./BankTransfer";
import { BankTransferFindManyArgs } from "./BankTransferFindManyArgs";
import { BankTransferWhereUniqueInput } from "./BankTransferWhereUniqueInput";
import { BankTransferUpdateInput } from "./BankTransferUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BankTransferControllerBase {
  constructor(
    protected readonly service: BankTransferService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BankTransfer })
  @nestAccessControl.UseRoles({
    resource: "BankTransfer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBankTransfer(
    @common.Body() data: BankTransferCreateInput
  ): Promise<BankTransfer> {
    return await this.service.createBankTransfer({
      data: data,
      select: {
        amount: true,
        createdAt: true,
        date: true,
        id: true,
        receiverBank: true,
        senderBank: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BankTransfer] })
  @ApiNestedQuery(BankTransferFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BankTransfer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async bankTransfers(@common.Req() request: Request): Promise<BankTransfer[]> {
    const args = plainToClass(BankTransferFindManyArgs, request.query);
    return this.service.bankTransfers({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        date: true,
        id: true,
        receiverBank: true,
        senderBank: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BankTransfer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BankTransfer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async bankTransfer(
    @common.Param() params: BankTransferWhereUniqueInput
  ): Promise<BankTransfer | null> {
    const result = await this.service.bankTransfer({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        date: true,
        id: true,
        receiverBank: true,
        senderBank: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BankTransfer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BankTransfer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBankTransfer(
    @common.Param() params: BankTransferWhereUniqueInput,
    @common.Body() data: BankTransferUpdateInput
  ): Promise<BankTransfer | null> {
    try {
      return await this.service.updateBankTransfer({
        where: params,
        data: data,
        select: {
          amount: true,
          createdAt: true,
          date: true,
          id: true,
          receiverBank: true,
          senderBank: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BankTransfer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BankTransfer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBankTransfer(
    @common.Param() params: BankTransferWhereUniqueInput
  ): Promise<BankTransfer | null> {
    try {
      return await this.service.deleteBankTransfer({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          date: true,
          id: true,
          receiverBank: true,
          senderBank: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
