/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InfluencerPageService } from "../influencerPage.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InfluencerPageCreateInput } from "./InfluencerPageCreateInput";
import { InfluencerPage } from "./InfluencerPage";
import { InfluencerPageFindManyArgs } from "./InfluencerPageFindManyArgs";
import { InfluencerPageWhereUniqueInput } from "./InfluencerPageWhereUniqueInput";
import { InfluencerPageUpdateInput } from "./InfluencerPageUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InfluencerPageControllerBase {
  constructor(
    protected readonly service: InfluencerPageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: InfluencerPage })
  @nestAccessControl.UseRoles({
    resource: "InfluencerPage",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInfluencerPage(
    @common.Body() data: InfluencerPageCreateInput
  ): Promise<InfluencerPage> {
    return await this.service.createInfluencerPage({
      data: data,
      select: {
        contentUrl: true,
        createdAt: true,
        description: true,
        followers: true,
        gifts: true,
        id: true,
        isBlocked: true,
        likes: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [InfluencerPage] })
  @ApiNestedQuery(InfluencerPageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "InfluencerPage",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async influencerPages(
    @common.Req() request: Request
  ): Promise<InfluencerPage[]> {
    const args = plainToClass(InfluencerPageFindManyArgs, request.query);
    return this.service.influencerPages({
      ...args,
      select: {
        contentUrl: true,
        createdAt: true,
        description: true,
        followers: true,
        gifts: true,
        id: true,
        isBlocked: true,
        likes: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: InfluencerPage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InfluencerPage",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async influencerPage(
    @common.Param() params: InfluencerPageWhereUniqueInput
  ): Promise<InfluencerPage | null> {
    const result = await this.service.influencerPage({
      where: params,
      select: {
        contentUrl: true,
        createdAt: true,
        description: true,
        followers: true,
        gifts: true,
        id: true,
        isBlocked: true,
        likes: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: InfluencerPage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InfluencerPage",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInfluencerPage(
    @common.Param() params: InfluencerPageWhereUniqueInput,
    @common.Body() data: InfluencerPageUpdateInput
  ): Promise<InfluencerPage | null> {
    try {
      return await this.service.updateInfluencerPage({
        where: params,
        data: data,
        select: {
          contentUrl: true,
          createdAt: true,
          description: true,
          followers: true,
          gifts: true,
          id: true,
          isBlocked: true,
          likes: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: InfluencerPage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InfluencerPage",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInfluencerPage(
    @common.Param() params: InfluencerPageWhereUniqueInput
  ): Promise<InfluencerPage | null> {
    try {
      return await this.service.deleteInfluencerPage({
        where: params,
        select: {
          contentUrl: true,
          createdAt: true,
          description: true,
          followers: true,
          gifts: true,
          id: true,
          isBlocked: true,
          likes: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
